In [1]:
import numpy as np

In [5]:
corr = np.array([[5,0,0],[0,8,0],[0,0,6]])

In [4]:
np.shape(corr)

(3, 3)

In [6]:
corr

array([[5, 0, 0],
       [0, 8, 0],
       [0, 0, 6]])

In [7]:
np.linalg.eig(corr)

(array([5., 8., 6.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))